### ISSUE TITLE
support chinese chess or not?

### ISSUE THREAD

**Issue by sandyplus** [andyruwruw/chess-image-generator#17]
Dear Andy,

Does your program support chinese chess?

Best regards,
sandy

**Comment by nearlySplat** [comment]
Do you mean [Shogi](https://en.wikipedia.org/wiki/Shogi)... or what

**Comment by hartwork** [comment]
@nearlySplat Shogi is Japanese, Chinese Chess is [Xiangqi](https://en.wikipedia.org/wiki/Xiangqi).

**Comment by andyruwruw** [comment]
Sorry it doesn't! But if you want to start your own library for Chinese chess, let me know if you need any help.

**Comment by hartwork** [comment]
@andyruwruw for chinese chess there is https://github.com/hartwork/xiangqi-setup .
